### ISSUE TITLE
Parameter default_install_dir is not used as default in INSTALL_PATH for installation command

### ISSUE THREAD

**Issue by costco-kynelson** [Dynatrace/Dynatrace-OneAgent-Puppet#46]
Defining `default_install_dir` does not tell the installer to install OneAgent to that install directory. This is because the command only respects `INSTALL_PATH` defined in `oneagent_params_hash` for creating the command arguments.

Not defining `INSTALL_PATH` but defining `default_install_dir` will break the install if the installer cannot install to the default `/opt/dynatrace/oneagent` directory, which is the reason you are defining `default_install_dir` in the first place, such as if you are installing to a directory on a separate mounted partition.

The `default_install_dir` parameter is used as the install directory in all other parts of the code correctly, so this seems unintended.

Install command is purely created from the `oneagent_params_hash` parameter.
```
      $oneagent_params_array    = $oneagent_params_hash.map |$key,$value| { "${key}=${value}" }
      $oneagent_unix_params     = join($oneagent_params_array, ' ' )
      $command                  = "/bin/sh ${download_path} ${oneagent_unix_params}"
```

Proposal:

Define `INSTALL_PATH` as the value of `default_install_dir` if `INSTALL_PATH` is not defined in `oneagent_params_hash`.

**Comment by luisr-escobar** [comment]
@costco-kynelson  thanks a lot for the feedback. `default_install_dir` is mostly used to track the install directory of the oneagent unless specified  as a key/value in  oneagent_params_hash , `INSTALL_PATH` does not need to be defined in oneagent_params_hash for either Windows, Ljnux or AIX which is why is not there by default therefore `default_install_dir` should never be passed as a parameter to the `dynatraceoneagent` class but instead `oneagent_params_hash` should be the only variable used for setting oneagent install parameters

**Comment by costco-kynelson** [comment]
Thanks for the explanation! I would propose not exposing default_install_dir as a parameter for the class if it's only used internally.
