### ISSUE TITLE
The download link throws an error on the download

### ISSUE THREAD

**Issue by phmcguin** [Dynatrace/Dynatrace-OneAgent-Puppet#5]
Error in Puppet:
Could not retrieve information from environment production source(s) https://myHost.live.dynatrace.com/e/myHost/api/v1/deployment/installer/agent/connectioninfo?Api-Token=myToken

**Comment by Polche** [comment]
Hello there,

Is this a known bug? We're getting the same error.

**Comment by MarcinZejer** [comment]
Hi, It looks to me, that download link was not updated or it is not valid. Description is provided readme file.

**Comment by fredjupp** [comment]
Hello,
This is a known issue  @puppetlabs. A workaround would be to use the remote_file provider from the forge instead of the file type from puppet itself. It can bypass the ssl validation (like curl -k) and works for all OSes
I already created a local branch with the changes, but am not able to push.
Here is my code snippet:
    # download the installer (requires remote_file provider from puppetforge)
    # current versions of dynatraceone only provide https dowload links
    # and ssl certs can not be verified. Puppet file type can not
    # handle these urls, so we changed to remote_file, which has an verify
    # peer option
    remote_file { 'dynatrace_installer_download':
      ensure      => present,
      source      => $download_link,
      path        => "${install_dir}/${installer}",
      verify_peer => false,
      require     => File[$install_dir]
    }

will do some testing, but i am positive, it will do

**Comment by TJM** [comment]
Our SSL certificate is valid, but that did not solve the issue either. I have several pull requests that fix several of the issues we had, but the vendor does not seem to maintain their own puppet module.

**Comment by luisescobar89** [comment]
fixed on latest version
