### ISSUE TITLE
Factor always returns nil

### ISSUE THREAD

**Issue by phmcguin** [Dynatrace/Dynatrace-OneAgent-Puppet#6]
The factor to check if ruxit is returns nil == version even if OneAgent is installed and the init.pp is written to always look for version = '0.0.0.0' instead of an actual version.

**Comment by TJM** [comment]
During a Puppet run, I see:

```
Info: Installed oneagent agent version -> '1.157.210.20181213-075558'
Info: Installed ruxit agent version -> '0.0.0.0'
```

Which correspond to the facts:

```
ruxit_installed_version => 0.0.0.0
oneagent_installed_version => 1.157.210.20181213-075558
```

The [init.pp](https://github.com/Dynatrace/Dynatrace-OneAgent-Puppet/blob/54cbd1066fb3a94a4dc1e7f9c8465008be2df83c/dynatraceoneagent/manifests/init.pp#L42) is written to check for 0.0.0.0 for *both* oneagent and runxit to see if it should install. Since they are not using proper packages, they have to resort to trickery like this. The "ruxit" fact is probably messed up, though.

**Comment by luisescobar89** [comment]
fixed on latest version
